[versions]
activityCompose = "1.12.0"
agp = "8.13.1"
androidxJunit = "1.3.0"
annotation = "1.9.1"
bcprovJdk15to18 = "1.82"
composeAnimation = "1.9.5"
composeBom = "2025.11.01"
coreKtx = "1.17.0"
datastore = "1.2.0"
documentfile = "1.1.0"
espresso = "3.7.0"
gson = "2.13.2"
hiddenapibypassVersion = "6.1"
hilt = "2.57.2"
hiltExt = "1.3.0"
jmdns = "3.6.2"
junit = "4.13.2"
kotlin = "2.2.21"
ksp = "2.2.20-2.0.3"
ktor = "3.3.2"
libsu = "6.0.0"
lifecycle = "2.10.0"
lottie = "6.7.1"
material = "1.13.0"
material3 = "1.5.0-alpha09"
materialIconsExtended = "1.7.8"
navigation = "2.9.6"
nayukiQR = "1.8.0"
room = "2.8.4"
securityCrypto = "1.1.0"
serialization = "1.9.0"
shizuku = "13.1.0"
slf4j = "1.7.36"
spake2Android = "-SNAPSHOT"
splashscreen = "1.2.0"
sunSecurityAndroid = "1.1"
work = "2.11.0"
kotlinGradlePlugin = "2.2.21"
appcompat = "1.7.1"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[libraries]
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-compose-animation = { group = "androidx.compose.animation", name = "animation", version.ref = "composeAnimation" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work" }
bcprov-jdk15to18 = { module = "org.bouncycastle:bcprov-jdk15to18", version.ref = "bcprovJdk15to18" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "materialIconsExtended" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }

